// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  startSidebar: [
    {
      type: 'category',
      label: '新手上路',
      items: [
        {
          type: 'autogenerated',
          dirName: '用户文档/新手上路',
        },
      ],
    },
  ],
  userSidebar: [
    {
      type: 'category',
      label: '用户文档',
      items: [
        '用户文档/用户手册入口',
        {
          type: 'autogenerated',
          dirName: '用户文档/任务流说明',
        },
      ],
    },
  ],
  devSidebar: [
    {
      type: 'category',
      label: '开发者文档',
      items: [
        {
          type: 'autogenerated',
          dirName: '开发者文档',
        },
      ],
    },
  ],
  aboutSidebar: [
    {
      type: 'category',
      label: '关于',
      items: [
        {
          type: 'autogenerated',
          dirName: '关于',
        },
      ],
    },
  ],
};

export default sidebars;
